import "./globals.css";
import type { Metadata } from "next";
import { AppTheme } from "@/themes/app/app.theme";

export const metadata: Metadata = {
  title: `${process.env.NEXT_PUBLIC_APP_NAME}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <AppTheme>{children}</AppTheme>
    </html>
  );
}
